# Change default connection username, password and database.
# Specify also host and port if not using tnsnames.ora connection.
default:
  username: tdd_test1
  password: tdd_test1
  database: xe
  # host: localhost
  # port: 1521

secondary:
  username: tdd_test1
  password: tdd_test1
  database: xe

different_user:
  username: tdd_test2
  password: tdd_test2
  database: xe
# Add other connection if needed.
# You can access them with plsql(:other) where :other is connection name specified below.

# other:
#   username: scott
#   password: tiger
#   database: xe
